### ISSUE TITLE
Use Jekyll or some other site generator to make site more appealing/functional?

### ISSUE THREAD

**Issue by FlxVctr** [OII-SDP-2016/oii_how_to_learn_to_code#4]
https://jekyllrb.com/

@cuducos: What do you think?

**Comment by cuducos** [comment]
Pretty easy to use, and it renders markdown to html automatically. I used it in [my personal page/blog](https://github.com/cuducos/cuducos.me), and people say it's quite easy to use with GitHub Pages (we might have to rename the repo to `OII-SDP-2016.github.io` though).

I can set it up but we should look for a CSS theme or something like that first… otherwise it would be just raw HTML without the swag.

**Comment by cuducos** [comment]
Maybe a very simple and straightforward look like this [Kasper theme](http://rosario.io/2013/11/10/kasper-theme-for-jekyll.html)?

![Kasper theme](https://raw.github.com/rosario/kasper/master/assets/images/kasper-theme-post.png)

**Comment by FlxVctr** [comment]
I agree to keep it minimalistic, but don't have any overview regarding what's out there. So just decide.
